# Generated by Django 4.2 on 2023-11-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0002_customuser_is_staff_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
