# Generated by Django 4.2 on 2023-10-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('not_confirmed', '確認前'), ('confirmed', '確認済'), ('completed', '来店済'), ('canceled', 'キャンセル済'), ('others', 'その他')], default='not_confirmed', max_length=50, verbose_name='ステータス'),
        ),
    ]
