# Generated by Django 4.2 on 2023-10-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0007_alter_slots_start_time'),
    ]

    state_operations = [
        migrations.DeleteModel("Slots"),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
