# Generated by Django 4.2 on 2023-10-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot_management', '0001_initial'),
        ('booking_management', '0008_delete_state'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='reservations',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slot_management.slots', verbose_name='予約枠'),
        ),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
