# Generated by Django 4.2 on 2023-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='namekana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
