# Generated by Django 4.2 on 2023-10-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0006_alter_slots_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='start_time',
            field=models.DateTimeField(unique=True, verbose_name='開始日時'),
        ),
    ]
